version: '3.8'

services:
  patient-service:
    build:
      context: ./patient-service
    ports:
      - "5003:5003"
    networks:
      - hospital-network

  doctor-service:
    build:
      context: ./doctor-service
    ports:
      - "5001:5001"
    networks:
      - hospital-network

  appointment-service:
    build:
      context: ./appointment-service
    ports:
      - "5002:5002"
    networks:
      - hospital-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    networks:
      - hospital-network

networks:
  hospital-network:
    driver: bridge
